Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
	
### Docker VM ###
  config.vm.define "docker" do |docker|
    docker.vm.box = "ubuntu/bionic64"
    docker.vm.hostname = "docker"
	docker.vm.network "private_network", ip: "192.168.56.15"
	docker.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
	 vb.cpus = 2
	 end
	docker.vm.provision "shell", path: "docker.sh"
  end

end
